### ISSUE TITLE
Game information as an Observer

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#101]
I'm building a PWA with a single scope, connecting to a server as observer and draw the battlefield, along with other useful information about the current match itself. Unfortunatly as an Observer Iḿ not able to know what is the size ofe the battlefield, or how many rounds there will be in total, ... alll the info that is contained in the GameSetup basically.

I would like to be able with my PWA to connect to a server in any moment, before or during a match, and still be able to draw the battlefield and showing the match. 

I think the best solution to give out the required info to an observer is to pass the GameSetup as soon as the observer connects, same as the BotListUpdate and same as the BotListUpdate, the GameSetup should be provided every time there's a change in it.

Let me know what you think @flemming-n-larsen and others
Cheers

**Comment by flemming-n-larsen** [comment]
@SirStone 

Currently, the server sends the `game-setup` whenever a new game is started. The Game Server send the [game-started-event-for-observer](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/game-started-event-for-observer.yaml) message in the [GameServer](https://github.com/robocode-dev/tank-royale/blob/main/server/src/main/kotlin/dev/robocode/tankroyale/server/core/GameServer.kt#L190-L197) class.

The `BotListUpdate` is send out whenever a bot joins or leaves the server, which can happen during a game. But the `game-setup` does not change during a game.

Hence, we could add the `game-setup` as a part of the [observer-handshake](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/observer-handshake.yaml) and [controller-handshake](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/controller-handshake.yaml).

This way, a controllers and observers gets the `game-setup` when a game is starting, and the would get it with the handshake, if a game has already started. If no games has started, `game-setup` will be `null`.

This should be very easy to add. 😊

**Comment by SirStone** [comment]
I think what you said works better than my idea. I would be very happy with
the solution to put the gameSetup into the handshake.

Hope it's easy enough to have it soon :P

Il Lun 19 Ago 2024, 21:13 Flemming N. Larsen ***@***.***> ha
scritto:

**Comment by flemming-n-larsen** [comment]
@SirStone 
It is easy, so I will start working on it. 😊

**Comment by flemming-n-larsen** [comment]
@SirStone This have been added with [release 0.24.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.24.2)

**Comment by SirStone** [comment]
Uhm I've tested connecting during a running game and during a paused game (still should be a valid game) but I could not see the GameSetup inside the ServerHandshake

![image](https://github.com/user-attachments/assets/207648e2-99e1-4af8-bd48-6693f8750e87)

**Comment by flemming-n-larsen** [comment]
@SirStone 
Ok. I will do something similar to ensure the `game-setup` is not missing.

**Comment by flemming-n-larsen** [comment]
@SirStone I did a new fix available in [release 0.24.3](https://github.com/robocode-dev/tank-royale/releases/tag/v0.24.3)

**Comment by SirStone** [comment]
I've checked succesfully that GameSetup is now visibile inside the ServerHandshake in case the join happens during a running match.
![image](https://github.com/user-attachments/assets/a1817d92-4568-48d2-b5e3-7a093b3f09b0)

Thanks Larsen.
I can see this improvement very useful for a future scenario where there's a running battle/tournament somewhere and _observer_s will be joining and leaving in any moment
