### ISSUE TITLE
Double TickEventForObserver received in V 0.24.1

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#102]
There's a bug in the latest version of the server 0.24.1
As Observer, and not sure if a Controller or Bot is affected, in version 0.24.1 (currently latest) I receive double ticks

Here a log of 3 consecutive ticks with version 0.24.0 (Good)
![RTR_0 23 2_good](https://github.com/user-attachments/assets/99e4a203-8453-4702-8209-e7395231e7fa)

Here a log of 4 consecutive ticks with version 0.24.1 (Bug)
![RTR_0 24 1_bug](https://github.com/user-attachments/assets/61f5cb94-1edc-4590-b396-c73d9b6a960b)

My code is the same in both examples, The difference is in the RTR booted version only.

**Comment by flemming-n-larsen** [comment]
@SirStone You are right. I was able to reproduce the issue, and have also found a fix for it.
 
 Thank you for reporting issues like this so we can get it fixed ASAP. 👍😊

**Comment by flemming-n-larsen** [comment]
@SirStone This should now be fixed with [release 0.24.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.24.2)

**Comment by SirStone** [comment]
@flemming-n-larsen tested and confirmed that this bug is no more

Closing!
