### ISSUE TITLE
Maybe small bug for ServerHandshake.version

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#104]
![version_too_loong](https://github.com/user-attachments/assets/01539a49-93ab-4e25-b87c-a295717f3790)

Don´t know if it's a bug or wanted feature but now the `version` field inside the ServerHandshake has the string "Robocode Tank Royale Server" added to the value.

If is not a bug, tell me I'll correct my code adapting to this change.

**Comment by flemming-n-larsen** [comment]
@SirStone This looks like a bug. 👍

**Comment by SirStone** [comment]
Problem solved

Thanks
