### ISSUE TITLE
Score vs Rank

### ISSUE THREAD

**Issue by russellpeiris** [robocode-dev/tank-royale#108]
Total Score does not determine the rank?

I simply used the robocode-tankroyale-gui-0.24.4.jar and sample bots.
1. Set rounds to 2+
2. Add 3+ bots
3. See scoreboard

**Expected behavior**
Highest scorer should receive 1st rank.

**Screenshots**
![image](https://github.com/user-attachments/assets/fb15ef13-dbf4-4a96-a136-634469a02fe1)

**Desktop (please complete the following information):**
 - Windows 11

**Java info:**
java 17.0.11 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)

**Comment by flemming-n-larsen** [comment]
@russellpeiris Thank you for the bug report. 🙂👍 
Looking at the scores/points, the order of looks correct. 
But you are right that the rank is wrong. So I will fix this for the next release. 🙂

**Comment by flemming-n-larsen** [comment]
@russellpeiris Fixed for the next release. 🙂

**Comment by flemming-n-larsen** [comment]
A fix for this issue is included in release [0.25.0](https://github.com/robocode-dev/tank-royale/releases/tag/v0.25.0)
