### ISSUE TITLE
Is there a Rust of this interface document?

### ISSUE THREAD

**Issue by 594872799** [robocode-dev/tank-royale#113]
https://robocode-dev.github.io/tank-royale/api/apis.html

**Comment by flemming-n-larsen** [comment]
There is no Rust implementation yet. But it is possible to communicate via the protocol over a WebSocket.

Schemas in JsonScema/YAML have been provided for the JSON messages that sent between the server, bots, and observer/controllers. And there are also sequence diagrams over, how the communication works:

https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/game/README.md
