### ISSUE TITLE
Server process consumes 100% of a CPU core even when game is paused

### ISSUE THREAD

**Issue by Cu3PO42** [robocode-dev/tank-royale#117]
**Describe the bug**
I just observed the server process taking up a full CPU core when running a battle, regardless of the configured tick speed or if the game is paused. I also observe that the battle cannot seem to run at over ~35 TPS. Admittedly, this isn't a terribly powerful machine and the network always introduces some delay, but I believe speeds over 100 TPS should be easily possible.

**To Reproduce**
1. Start a server, GUI as well as two Walls bots.
2. Start a battle.
3. Pause the battle.
4. Look at task manager/resource monitor/...

**Expected behavior**
While the battle is paused, the server should use minimal CPU time. When running the battle, it should depend on the configured tick speed.

**Desktop (please complete the following information):**
 - NixOS 24.11 (Linux Kernel 6.12)

**Java info:**
 - Version: 21
- Vendor: OpenJDK

**Additional Context:**  
Both the GUI and server processes show resource consumption that falls within expectations.

**EDIT**: I just observed that the lower I set the turn timeout, the faster does the battle actually run (without bots skipping any turns). In fact, there appears to be an inverse correlation.

This leads me to the following hypothesis: a turn will not just take at most as long as the timeout, it will also take roughly at least as long, capping the maximum TPS.

**Comment by Cu3PO42** [comment]
I believe I figured out why the turn timeout limits the speed the battles can run at. Currently, the timeout is the only thing calling `GameServer#onNextTurn`.

`GameServer#handleBotIntent` checks if all intents for the turn have been received and calls `resetTurnTimeout` in that case. Unfortunately, `resetTurnTimeout` only checks if the period of the timeout needs to be adjusted (which generally it doesn't need to be) and does nothing. Simply adding a call to `onNextTurn` likely fixes that issue.

I will test my proposed fix tomorrow. However, I don't currently think this is the reason for the extremely high CPU usage.

**Comment by Cu3PO42** [comment]
The high resource consumption is due to a busy wait in `NanoTimer`. I'm working on fixes for the issues raised here and will send a PR later.

**Comment by flemming-n-larsen** [comment]
@Cu3PO42
This could be OS specific, as I have not run into this issue, at least on Windows 11.

`onNextTurn()` is called on each game tick controlled by the timer. So it should not be called anywhere else. The bots have a guarantee that they can use up to X amount of time per turn. So that is why the timer is crucial.
`resetTurnTime` is calculated, as the user might change the TPS mid game.

If all bots have sent their intent for the turn, there is no reason to wait for the next turn, as all bots are ready for the next turn, and hence we can reset the turn timer.

**Comment by Cu3PO42** [comment]
I can reproduce the behavior on Windows 11 as well: 
![grafik](https://github.com/user-attachments/assets/a754a52e-51ff-4237-9c32-cad2065f9e94)

It might not be as apparent because the server does not show up as part of the Robocode applicaiton, but it's also using roughly one full CPU core here while the game is paused. I am honestly quite relieved it happens on Windows as well, because I could not imagine any reason at all why the busy waiting I found would be platform specific.

> If all bots have sent their intent for the turn, there is no reason to wait for the next turn, as all bots are ready for the next turn, and hence we can reset the turn timer.



Absolutely, but the timer reset did not trigger execution of the `onNextTurn` method. Hence the next turn would only start when the bots have sent their intents AND the freshly reset timer elapses (assuming that all bots send their intent in time). This drastically limits the maximum tick speed. For reference, here's a screen recording of RTR running a battle between two Walls bots on a PC with a 5800X3D CPU: 

https://github.com/user-attachments/assets/7781d4ee-2bce-4027-8f58-5b0d0783e1fc

There is also another reason to wait after all bots sent their intent: to achieve the desired TPS if the bots are faster than necessary.

I am working on a revision that takes all of this into account.

**Comment by flemming-n-larsen** [comment]
I of course agree that the next turn can be executed (calling `onNextTurn`) when all bots have sent their intent.
If the game is set to max TPS (-1), this becomes very important.

Also note that the user might set the game to e.g. 1 TPS (e.g. when debugging), but the bots still need to obey the allowed turn time limit, where the intent must be sent, even when 1 TPS gives the bots more time.

I look forward to see if you succeed in fixing the issue. 🙂

**Comment by flemming-n-larsen** [comment]
@Cu3PO42 

I am very impressive with your work. 🤩
And now I do see the busy waiting, which was definitely bad code!

I have tested it, and it seems to work really smoothly. And I don't think we need any follow-up PR.

I did make a minor change replacing `Thread.sleep(Duration)` as this is first supported from Java 19, and the minimum requirement for Tank Royale is currently Java 11. I just replaced it with `TimeUnit.NANOSECONDS.sleep(long)` which does the same work. Of course we should not stick to Java 11 forever, but in this case we don't need to upgrade to Java 19.

I also want to refactor the `run()` method into smaller pieces so the code is easier to grasp, and to avoid redundant code as well. I will put in the code suggestion for you, so you can see my suggestion.

**Comment by flemming-n-larsen** [comment]
Released with version [0.27.0](https://github.com/robocode-dev/tank-royale/releases/tag/v0.27.0)
