### ISSUE TITLE
Add stepping turn-by-turn if battle is paused

### ISSUE THREAD

**Issue by beamer159** [robocode-dev/tank-royale#13]
When debugging a bot, it is helpful to observe what it does one turn at a time. The game already implements pausing a battle, which helps a lot. This could be expanded on by allowing paused matches to progress by one turn per hotkey/button press.

**Comment by flemming-n-larsen** [comment]
Agree. This is essential to debugging. 😊

**Comment by flemming-n-larsen** [comment]
I added this  feature with version 0.12.0 available [here](https://github.com/robocode-dev/tank-royale/releases/tag/v0.12.0) 🙂

**Comment by beamer159** [comment]
Works great, thanks for implementing!
