### ISSUE TITLE
json $type field problematic with python code generation

### ISSUE THREAD

**Issue by stobias123** [robocode-dev/tank-royale#31]
**Describe the bug**
I'm trying to generate some python clients from the given json schema. I'm using https://github.com/koxudaxi/datamodel-code-generator/ , and the `$type` field is giving me lots of grief. 

Since python can't use special chars in var/param names, I'm wondering if there's some reason this field needs to have a `$`? 

**Error info**
All sorts, there's no easy code gen from existing json schema tooling.

**Comment by flemming-n-larsen** [comment]
That is a good point Steven. 👍 
The $type should not get in the way when using it with other programming languages and parsers.
So I will see if I can fix this to a better name without a special character in front of "type".

**Comment by flemming-n-larsen** [comment]
@stobias123, I have changed `$type` into `type` on the master branch.
I hope this works better for you?

**Comment by stobias123** [comment]
@flemming-n-larsen - yes perfect thank you! I was running a local fork over the weekend with that same change.

**Comment by flemming-n-larsen** [comment]
> @flemming-n-larsen - yes perfect thank you! I was running a local fork over the weekend with that same change.

Cool. Then we are sure it will work.
Thank you for reporting this issue, so we could get it fixed. 🙂
