### ISSUE TITLE
Fire and Explosion Sounds

### ISSUE THREAD

**Issue by whatevergeek** [robocode-dev/tank-royale#4]
Hi,

First of all, thank you for creating an upgraded platform for robocode.
I love it! especially the fact that it enables me to use the latest .NET Framework.

Regarding sound (Firing and Tank Explosions), just wanted to inquire if this is already in place and perhaps my setup hasn't just enabled it (i.e. no sound by default). or there is really no sound as per the latest version?

feel free to reply and close when you get some time :-)
stay awesome!

**Comment by flemming-n-larsen** [comment]
Sound has not been added yet. But it should be easy to add to Tank Royale.
The hard part will be to find some available sounds that fit Robocode and can be used for free.

I guess a enable/disable sound option + volume should also be added to this feature.

**Comment by beamer159** [comment]
Consider Kenney Game Assets for free audio samples. There license is open:

https://kenney.nl/support

> **Is it possible to use the game assets in a (commercial) project?**
> 
> All game assets on this website are [public domain CC0](https://creativecommons.org/publicdomain/zero/1.0/) licensed, see the included license file or refer to the game asset page for full details.
[sounds.zip](https://github.com/robocode-dev/tank-royale/files/8289925/sounds.zip)

As for specific audio samples to use, consider the [Sci-Fi Sounds](https://kenney.nl/assets/sci-fi-sounds) and [Impact Sounds](https://kenney.nl/assets/impact-sounds) packs. Attached below are some examples of sounds from these packs that could make sense for the game.

[sounds.zip](https://github.com/robocode-dev/tank-royale/files/8289927/sounds.zip)

**Comment by flemming-n-larsen** [comment]
Thank you. I will have a look into this later when I need to add some audio. 😊

**Comment by flemming-n-larsen** [comment]
@whatevergeek 
Sounds has finally been implemented in Tank Royale with version [0.17.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.17.2).

**Comment by whatevergeek** [comment]
This is awesome! thank you very much @flemming-n-larsen  !
I'll try to get the new version now :-)
