### ISSUE TITLE
Bots in Bot Directories can't join the battle

### ISSUE THREAD

**Issue by manimonji** [robocode-dev/tank-royale#5]
**Describe the bug**
when you want to start a battle, you may choose bots are in bot directories, but you only can choose from joined bots(i dont know what is this means). but you can start bots local (i dont know what is this).

**Comment by flemming-n-larsen** [comment]
I need some more information about the issue.

- Bots can join your server from your network/the Internet. All bots joining the server are listed in the "Joined bots".
- The "Bot Directories" lists all the bots found on your system that you have added to the game.
- The "Running bots (locally)" shows the bots you have booted from your system. As soon as they boot (correctly), they will join the server.
- With "Selected bots" you choose which of the joined bots you want to battle and press "Start Battle".

I guess I will need to add some documentation/guide in how to use the UI.

**Comment by flemming-n-larsen** [comment]
@manimonji 
I have made a description of how to use the GUI application. I hope this helps to understand it?
https://robocode-dev.github.io/tank-royale/articles/gui.html#gui-application

**Comment by manimonji** [comment]
Thanks @ flemming-n-larsen, it helped me a lot! But it is difficult to read some texts on the website. I know you're not a web developer, but you need to fix the site's interface. I'm a web developer if you want I can improve the site user interface! Do not consider this an insult

**Comment by flemming-n-larsen** [comment]
@manimonji 
Thank you for the feedback. 🙂

I do not consider it as an insult, but constructive feedback for how to improve the documentation, which I appreciate.
I welcome help with improving the documentaion. So you are welcome to give it a shot doing a PR. Perhaps a small one to begin with to understand what you are trying to achive first.

The [Robocode Tank Royale Docs](https://robocode-dev.github.io/tank-royale/) is made with [VuePress](https://vuepress.vuejs.org/) using plain markup and plugins, which makes it easy to write documentation the same way as the ReadMe.md files. I want to stick with the markdown syntax and keep it simple to maintain the documentation.

And it is important to incorporate the various documentations from e.g. [Javadoc](https://www.baeldung.com/javadoc) and [Docfx](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html), i.e. generated static HTML.

**Comment by flemming-n-larsen** [comment]
I see we should continue the talk on [Discussin #18](https://github.com/robocode-dev/tank-royale/discussions/18)
