### ISSUE TITLE
at each tick the bots receives the full list of bullets

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#53]
**Describe the bug**
As far as I know the bullets of other bots should be invisible to the bot but right now at each tick, inside the 
[tick-event-for-bot](https://github.com/robocode-dev/tank-royale/blob/master/schema/schemas/tick-event-for-bot.yaml) there are the bullets of other bots too

**To Reproduce**
I'm seeing this because I'm develping a full botApi in a different language so I can't explain step by step, if you read any tick-event-for-bot while any bullet is on the field you will see that those bullets are included in the bulletStates

**Expected behavior**
the bulletStates inside the tick-event-for-bot must contain only the bullets owned by the bot that shoot them

**Print out**
example of 2 consecutive ticks I've captured

TICK T
(bulletId: 3, **ownerId: 1,** power: 1.0, x: 249.4709461593531, y: 344.0048802302621, direction: 148.5360218511403, color: "")
my id is **2**

TICK T+1
(bulletId: 3, **ownerId: 1,** power: 1.0, x: 234.9704818187843, y: 352.8782411441377, direction: 148.5360218511403, color: "")
my id is **2**

**Robocode Server version**
Robocode Tank Royale Server 0.17.4

**Comment by flemming-n-larsen** [comment]
@SirStone Thank you for both discovering and reporting this issue.
Of course, the bugs must not be able to see the bullets of the other bots, so this must be fixed ASAP.

**Comment by flemming-n-larsen** [comment]
@SirStone This should be fixed now with the release of version [0.18.0](https://github.com/robocode-dev/tank-royale/releases/tag/v0.18.0)

**Comment by flemming-n-larsen** [comment]
@SirStone I consider this issue as solved. Otherwise, just re-open it. 🙂
