### ISSUE TITLE
BulletHitBotEvent vs HitByBulletEvent

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#59]
**Describe the bug**
Bot API allows to use [onHitByBullet](https://robocode-dev.github.io/tank-royale/api/java/dev/robocode/tankroyale/botapi/IBaseBot.html#onHitByBullet(dev.robocode.tankroyale.botapi.events.HitByBulletEvent))​([HitByBulletEvent](https://robocode-dev.github.io/tank-royale/api/java/dev/robocode/tankroyale/botapi/events/HitByBulletEvent.html) hitByBulletEvent)
But the bot receives the BulletHitBotEvent instead:
> {"victimId":1,"bullet":{"bulletId":10,"ownerId":3,"power":2.0,"x":388.9596630220835,"y":582.0,"direction":0.0,"color":"#008000"},"damage":10.0,"energy":42.59999999999999,"turnNumber":167,"type":"BulletHitBotEvent"}

**Expected behavior**
Expecting to receive as bot a HitByBulletEvent
Leave the BulletHitBotEvent for Controllers and Observers

**Additional context**
YAML of the 2 events for easy comparison of the contents
[bullet-hit-bot-event](https://github.com/robocode-dev/tank-royale/blob/master/schema/schemas/bullet-hit-bot-event.yaml)
[hit-by-bullet-event](https://github.com/robocode-dev/tank-royale/blob/master/schema/schemas/hit-by-bullet-event.yaml)

**Comment by flemming-n-larsen** [comment]
I understand your confusion. But this is _by design_ (on purpose). 💡
So I will not change this, and it is not a bug. 🙂

In the protocol/schemas, I only have BulletHitBotEvent, but within the APIs I check the victim id and decide if it should be a HitByBulletEvent or BulletHitBotEvent:

```java
    private static BotEvent map(final dev.robocode.tankroyale.schema.BulletHitBotEvent source, int myBotId) {
        BulletState bullet = BulletStateMapper.map(source.getBullet());
        if (source.getVictimId() == myBotId) {
            return new HitByBulletEvent(
                    source.getTurnNumber(),
                    bullet,
                    source.getDamage(),
                    source.getEnergy());
        }
        return new BulletHitBotEvent(
                source.getTurnNumber(),
                source.getVictimId(),
                bullet,
                source.getDamage(),
                source.getEnergy());
    }
```
So I am "reusing" the BulletHitBotEvent in the schema to represent two events in the API to make it easier for the user. But from the controller and server, it does not really matter.

I did the same thing for DeathEvent and BotDeathEvent:

```java
    private static BotEvent map(final dev.robocode.tankroyale.schema.BotDeathEvent source, int myBotId) {
        if (source.getVictimId() == myBotId) {
            return new DeathEvent(source.getTurnNumber());
        }
        return new BotDeathEvent(source.getTurnNumber(), source.getVictimId());
    }
```

So the APIs are not necessarily a 1-1 mapping of the schemas/protocol. I just _chose_ to make this distinction with the Bot APIs that are the default reference implementations of Bot APIs. 🙂

**Comment by SirStone** [comment]
Good to know, I had a thought that this was the case. Closing
