### ISSUE TITLE
Server is not accepting the full range of ports

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#66]
**Describe the bug**
The range ports for a standard computer is 1-65535 but the server uses a Short to store the port so the port can't have a port over the maximum positive short, that is 32767, leaving out 65535-32767=32768 unusable ports

**To Reproduce**
FAIL
launch the server with the maximum short+1=32768 and it will fail wiht the message "Invalid value for option '--port': '32768' is not a short"
`java -jar robocode-tankroyale-server-0.19.1.jar --botSecrets veuogdpgjtd --controllerSecrets ifrafjbrpcg --port 32768`

NO FAIL
launch the server with the maximum short = 32767 and the server will start ok
`java -jar robocode-tankroyale-server-0.19.1.jar --botSecrets veuogdpgjtd --controllerSecrets ifrafjbrpcg --port 32767`

**Expected behavior**
The server should be able to use any port out of the full range

**Screenshots**
![Screenshot 2023-03-26 at 11 34 16](https://user-images.githubusercontent.com/1309932/227767194-f217e4c0-815e-4b62-a300-106f9837af4e.png)

**Comment by flemming-n-larsen** [comment]
@SirStone Thank you for reporting this. I will fix it ASAP.

**Comment by flemming-n-larsen** [comment]
Fixed with the [0.19.2 release](https://github.com/robocode-dev/tank-royale/releases/tag/v0.19.2)
