### ISSUE TITLE
Cannot import Maven dependency dev.robocode.tankroyale:robocode-tankroyale-bot-api:0.10.0

### ISSUE THREAD

**Issue by beamer159** [robocode-dev/tank-royale#7]
**Describe the bug**
Maven dependency `dev.robocode.tankroyale:robocode-tankroyale-bot-api:0.10.0` cannot be imported into a Java project. It looks like groupId `dev.robocode.tankroyale` contains only one artifactId: `robocode-tankroyale-bot-api`. However, this artifact's pom depends on another artifact that should be in this group: `dev.robocode.tankroyale:robocode-tankroyale-schema:0.10.0`

**To Reproduce**
Steps to reproduce the behavior (Intellij IDEA):
1. Create a Gradle project
2. In `build.gradle`, in the `dependencies` block, add `implementation 'dev.robocode.tankroyale:robocode-tankroyale-bot-api:0.10.0'`
3. Load Gradle changes

**Error info**
```
GradleBot:main: Could not find dev.robocode.tankroyale:robocode-tankroyale-schema:0.10.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/dev/robocode/tankroyale/robocode-tankroyale-schema/0.10.0/robocode-tankroyale-schema-0.10.0.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project : > dev.robocode.tankroyale:robocode-tankroyale-bot-api:0.10.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Desktop (please complete the following information):**
Windows 11

**Java info:**
Oracle v.17

**Comment by flemming-n-larsen** [comment]
I did a similar setup to reproduce the issue, and I can confirm that the Bot API cannot be downloaded from Maven.
I will look into this.

**Comment by flemming-n-larsen** [comment]
With the new release 0.11.0 it should now be possible to use the Maven dependency dev.robocode.tankroyale:robocode-tankroyale-bot-api:0.11.0. I tested this locally.

For some reason, version 0.11.0 does not show up when searching for the artifact? I might need to do a new release to fix this, as OSSRH does not allow me to update version 0.11.0 when it has been released. I got the same issue for 0.10.0.

**Comment by beamer159** [comment]
I am getting the same issue as last time:

```
Could not find dev.robocode.tankroyale:robocode-tankroyale-schema:0.11.0
```

Looking at the [Maven repo for dev.robocode.tankroyale](https://repo.maven.apache.org/maven2/dev/robocode/tankroyale/), this schema artifact is not there, only the api artifact is.

In the meantime, could you provide a local jar file and javadoc for 0.11.0?

**Comment by flemming-n-larsen** [comment]
Hmm... something is definitely broken  when the artifact is uploaded on Sonatype.
I will need to find a good way to reproduce this issue locally so it can be solved once and for all.

**Comment by flemming-n-larsen** [comment]
Quick update on the topic.
I realised that I cannot put fat jars on Maven. At least it is bad practise. Hence, I will rework the way the artifacts are build and published in order to fix the real issues.

**Comment by flemming-n-larsen** [comment]
@beamer159 
It seems to work with version 0.11.1 available at the Maven Repository [here](https://mvnrepository.com/artifact/dev.robocode.tankroyale/robocode-tankroyale-bot-api/0.11.1).

The issue was the pom.xml file that contained explicit dependencies, which it should not, as everything is contained within the jar file.

**Comment by beamer159** [comment]
This seems to be resolved now. Thanks for fixing.
