### ISSUE TITLE
New version 0.21.0 freezes starting battle

### ISSUE THREAD

**Issue by martinezpenya** [robocode-dev/tank-royale#75]
**Describe the bug**
New version 0.21.0 freezes starting battle

**To Reproduce**
Launch 0.21.0 version gui jar from Kubuntu 22.04LTS, go to Battle, Start Battle... the app freezes, you can't select bots from samples bot and boot them. I have to close the app by the force. No error or debug information on console

**Error info**
No error shown

**Expected behavior**
Select bots, boot them and start battle, with version 0.19.3 it works very well.

**Screenshots**
non applicable

**Desktop (please complete the following information):**
 - OS name and version: Kubuntu 22.04 LTS

**Java info:**
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)

**Additional context**
nothing exceptional

**Comment by flemming-n-larsen** [comment]
@martinezpenya Thank you for reporting this. I will have a look ASAP.

**Comment by martinezpenya** [comment]
If I can help you in any way, let me know. Launching in debug mode, or get logs...

**Comment by flemming-n-larsen** [comment]
@martinezpenya Thanks. I have made a workaround and uploaded a new [robocode-tankroyale-gui-0.21.0.1.jar](robocode-tankroyale-gui-0.21.0.1.jar). 
I basically uncommented the code for the BusyPointer with activate and deactivate, which causes the issue somehow:
https://github.com/robocode-dev/tank-royale/blob/123a495fd28a4d5f33309dbcb58903dec1c1548d/gui-app/src/main/kotlin/dev/robocode/tankroyale/gui/util/GuiTask.kt#L9

Now I need to fix this issue so it works well on both Windows, Linux (Ubuntu), and Mac OS. I think I am going to rewrite the way to handle the busy pointer.

**Comment by martinezpenya** [comment]
Thank you, I can confirm you that 21.0.1.jar works well on kubuntu 22.04 LTS. Thank you!
