### ISSUE TITLE
GUI: Unreadable Server Log on NixOS

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#77]
**Describe the bug**
Dunno if this is only on my machine but when I open the server logs in the GUI I see white characters on a light grey background, making the all logs not readable if not highlighted or copied somewhere else.

**To Reproduce**
open the GUI, run a server and open "Show Server Log"

**Screenshots**
![Screenshot from 2023-11-12 15-39-44](https://github.com/robocode-dev/tank-royale/assets/1309932/23765614-d712-46cb-8cef-d42e999ceb25)

**Desktop (please complete the following information):**
 Apple Inc. MacBookPro9,2
NixOS 23.05
GNOME Version 44.2
Windowing System Wayland
Kernel Version 6.1.61

**Java info:**
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35)
OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)

**Additional context**
I want emphasize that this could be really caused by my desktop. I don't even want to push on this, I don't really need to se these logs right now.

**Comment by flemming-n-larsen** [comment]
It seems like it is the background color that is wrong and not the text color. The background color should have been dark grey.
I am using a JEditorTextPane with HTML content and CSS stylesheets. I bet the background color needs to be set as a style.

**Comment by flemming-n-larsen** [comment]
I made some fixes for the Server Log, which I have verified on Windows and Ubuntu/Linux.

You can try out this beta version:
https://robocode.dev/tankroyale/files/robocode-tankroyale-gui-0.21.2-beta.jar

If it works, I will make a new release containing this fix. 🙂👍

**Comment by SirStone** [comment]
Nope, and looking for the version from the GUI I've found out that even the "About" page is white over light gray background
![image](https://github.com/robocode-dev/tank-royale/assets/1309932/0c293fdb-f165-476b-9f17-472c8cc3ebe4)

**Comment by flemming-n-larsen** [comment]
Thank you for the follow-up. I will see if setting the background as well might fix the issue, so I will upload another version soon.
This issue is weird, as it works for, e.g. Ubuntu/Linux and the WSL running on Ubuntu with an X server. But this is no excuse for the bug. It needs to be fixed. 😉

**Comment by flemming-n-larsen** [comment]
@SirStone 
Okay. I have now made another version, where I set the background colors for the Server console (and bot console) + about box.
Here is an updated version containing this fix:
https://robocode.dev/tankroyale/files/robocode-tankroyale-gui-0.21.2-beta-2.jar

If this does not work, I need to use an entirely other solution to make it work.

**Comment by SirStone** [comment]
Now I see the "about" page fixed but the console is still messed up, but differently, the green part is not my highlighting, it came out like this on it's own. 
![image](https://github.com/robocode-dev/tank-royale/assets/1309932/d4e9aa03-60a0-4d1d-bb2e-8049053caea3)

**Comment by flemming-n-larsen** [comment]
Thank you for the follow-up. Okay. So at least some progress with the about box.
I did set the text color to black in this case.
With the bot console, both the background color of the panel and the CSS have been set to dark grey. So it is strange it does not work on your system.

I will try something else later.

**Comment by flemming-n-larsen** [comment]
@SirStone I have now installed NixOS 23.05 (on VirtualBox) and installed the Open JDK (nixos.openjdk17-bootstrap).
This is a snapshot from the server console. I get the green markings like you, but I do get the correct background color:

![image](https://github.com/robocode-dev/tank-royale/assets/2179727/641cabc9-53c0-4759-9ed0-7999857d8dea)

I will try to use the Zulu version as well, which I expect to cause the issue.

**Comment by flemming-n-larsen** [comment]
I have now removed the Open JDK and use the Zulu Java vendor (nixos.zulu) instead.

Here I see the same issue with the background color missing. So the issue exist when using the Zulu version of Java.
I will see if I can fix it, when I am able to see it on my local machine. 🙂

**Comment by SirStone** [comment]
yes! It works!
![Screenshot from 2023-12-04 22-51-39](https://github.com/robocode-dev/tank-royale/assets/1309932/77993f3c-c63d-4d3d-932a-1ed0953acc99)

Thanks Larsen, you're the best! (and destroy the rest!) :P

**Comment by flemming-n-larsen** [comment]
> yes! It works! ![Screenshot from 2023-12-04 22-51-39](https://private-user-images.githubusercontent.com/1309932/287853998-77993f3c-c63d-4d3d-932a-1ed0953acc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzMzMzgsIm5iZiI6MTcwMTczMzAzOCwicGF0aCI6Ii8xMzA5OTMyLzI4Nzg1Mzk5OC03Nzk5M2YzYy1jNjNkLTRkM2QtOTMyYS0xZWQwOTUzYWNjOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMjMzNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNjMGE3ODJlNjc4MTRiOTE3MWEwNjNlZWEzMjhiZDFiODAxY2RlNzVmYzk5ZjdjNmFhNTdiMTE3OWIyZmYzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fRLYiXCOMifgu22NipATA0WvXbXKm6ICprSnLikP6cw)
> 
> Thanks Larsen, you're the best! (and destroy the rest!) :P

Haha... Thank you for the feedback 👍😊

**Comment by SirStone** [comment]
mmm I need to reopen this.
I can't say if I noticed this after the updates or was already present before. Looks like the bug affecting the logs and others components is affecting the `popups`.
Here some screenshots:
### mouse over TPS
![mouse over TPS](https://github.com/robocode-dev/tank-royale/assets/1309932/a6131b48-a3d6-46bc-bde3-e8f3f0022a6d)

### mouse over the bot
![Screenshot from 2023-12-24 11-56-21](https://github.com/robocode-dev/tank-royale/assets/1309932/833b5a56-ae93-4a99-80ae-ada7dd077d7a)

**Comment by flemming-n-larsen** [comment]
@SirStone 
This is a new issue. The old one #77 has been fixed, but you definitely discovered a new one.
Hence, I have created #81 to cover the new one, and I close this one.
