### ISSUE TITLE
Booting/unbooting robots not working

### ISSUE THREAD

**Issue by beamer159** [robocode-dev/tank-royale#89]
**Describe the bug**
Only one robot can be booted at a time. This robot cannot be unbooted. Also, restarting the server does not unboot the robot.

https://github.com/robocode-dev/tank-royale/assets/7436252/2a57b53a-d1ad-4b06-ad93-01052918dfc3

**Comment by flemming-n-larsen** [comment]
@beamer159 Thank you for reporting this. 👍
I will work on fixing this asap.

**Comment by flemming-n-larsen** [comment]
@beamer159:
I fixed the issue with [version 0.23.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.23.2). 😊

**Comment by flemming-n-larsen** [comment]
@beamer159 
Strange. It seems like the archive file for the GUI did not build correctly. Hence, I have now rebuild it and re-created the release. And also downloaded the archive an ran it locally on another system to verify that it is indeed the correct version.

So it seems to work on my side after the re-release of the archive.

Try again with [version 0.23.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.23.2). 🙂

**Comment by beamer159** [comment]
It's working for me now, thank you for the quick response

**Comment by flemming-n-larsen** [comment]
@beamer159
 Thank you for the quick feedback that it still had issues. 🙂👌
 And I am sorry for the bad setup file. 🫣
