### ISSUE TITLE
Schema inconsistencies

### ISSUE THREAD

**Issue by beamer159** [robocode-dev/tank-royale#92]
https://github.com/robocode-dev/tank-royale/blob/97be0048e8736c9ef22037904d53a92c0631a293/schema/schemas/game-started-event-for-bot.yaml#L13-L15

Description should be `Start y coordinate`

---

`maxInactivityTurns` and `isMaxInactivityTurnsLocked` defined here:

https://github.com/robocode-dev/tank-royale/blob/97be0048e8736c9ef22037904d53a92c0631a293/schema/schemas/game-setup.yaml#L47-L53

But the required section names them differently: `inactivityTurns` and `isInactivityTurnsLocked`

https://github.com/robocode-dev/tank-royale/blob/97be0048e8736c9ef22037904d53a92c0631a293/schema/schemas/game-setup.yaml#L84-L85

**Comment by flemming-n-larsen** [comment]
@beamer159 
Thank you for notifying me about this. 
I have fixed it now. 😊
