### ISSUE TITLE
 Schema inconsistencies 2

### ISSUE THREAD

**Issue by SirStone** [robocode-dev/tank-royale#94]
Sorry, I've stolen the title from the last closed bug, but the issue is on the same page of that one. I've found about this when I've completed a script that converts your yaml schemas to my nim needs.

The schema [results-for-bot.yaml](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/results-for-bot.yaml) has **id** _bot-results-for-bot.yaml_ <-- id is different from the file name
The schema [game-ended-event-for-bot.yaml](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/game-ended-event-for-bot.yaml) references for the **results** to _results-for-bot.yaml_

I think that the **id** of the  [results-for-bot.yaml](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/results-for-bot.yaml) should be changed in  _results-for-bot.yaml_

**Comment by SirStone** [comment]
Another one surfing the repo, [bullet-hit-bot-event.yaml](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/bullet-hit-bot-event.yaml) has a wrong id
![Schermata del 2024-06-16 16-01-13](https://github.com/robocode-dev/tank-royale/assets/1309932/f6b68d2c-e549-4520-bd1b-3bf1609cef5f)

**Comment by SirStone** [comment]
Third one, [bot-hit-bot-event.yaml](https://github.com/robocode-dev/tank-royale/blob/main/schema/schemas/bot-hit-bot-event.yaml) has different id
![Schermata del 2024-06-16 16-07-57](https://github.com/robocode-dev/tank-royale/assets/1309932/224d1f7b-9523-4b1c-b389-0c78229d2ede)

**Comment by flemming-n-larsen** [comment]
@SirStone 
Thank you for reporting this. 🙂👍

I have fixed the issue with this commit:
https://github.com/robocode-dev/tank-royale/commit/6acef2909f86daa306d223bb664799cf112fe752

**Comment by SirStone** [comment]
Thanks, I will wait for the next release to check on this.

**Comment by flemming-n-larsen** [comment]
@SirStone 
Just released [0.24.1](https://github.com/robocode-dev/tank-royale/releases/tag/v0.24.1) where the schemas are updated.

**Comment by SirStone** [comment]
Thanks for the update
I've tested the new schemas and now I think are ok but for a missing event: hit-by-bullet-event that is generated by the API and not from the Server.

I was trying to "pull request"  but I ended up making a direct push to the main branch...I didn´t know I had this permission...

I've just uploaded a single new file, hope is not an issue. [7db15b4](https://github.com/robocode-dev/tank-royale/commit/7db15b44d8ffdeb5493fb9c0accbd210bdf915ac)

**Comment by flemming-n-larsen** [comment]
@SirStone: The changes look good to me. You are right that I just generate the event on the server side. And I guess I do that for a few of the events. But this does not mean that we should leave out the schemas. So I think it is perfectly okay to add it like you did. Thanks. 👍🙂

If I disable the write permission, you will not be able to update the Wiki.
But I will remove it now - at least temporarily to avoid accidental writes to main. 😉
Then I will just grant you write permission again late, if needed.

I recommend that you create a fork of Robocode, or create (feature) branches instead of working on main. This also makes it possible to compare changes against the main branch etc. 🙂

**Comment by flemming-n-larsen** [comment]
@SirStone: I put you in the role: Triage. Let's see how this goes. 😊

**Comment by flemming-n-larsen** [comment]
Closing this issue now.
